# Generated by Django 2.2.3 on 2019-07-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iteninary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('iteninary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteninary.Iteninary')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bus', 'Bus'), ('Taxi', 'Taxi'), ('Car', 'Car'), ('Train', 'Train'), ('Plane', 'Plane')], max_length=5)),
                ('price', models.FloatField()),
                ('provider', models.CharField(max_length=70)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteninary.Path')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=40)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteninary.Path')),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Hostel', 'Hostel'), ('Hotel', 'Hotel')], max_length=6)),
                ('price', models.FloatField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteninary.Path')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Hiking', 'Hiking'), ('Camping', 'Camping'), ('Sightseeing', 'Sightseeing'), ('Mountaining', 'Mountaining'), ('Sailing', 'Sailing'), ('Biking', 'Biking'), ('Fishing', 'Fishing')], max_length=11)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteninary.Path')),
            ],
        ),
    ]
