# Generated by Django 2.2.3 on 2019-07-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteninary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='path',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='path',
        ),
        migrations.RemoveField(
            model_name='path',
            name='iteninary',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='path',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='path',
        ),
        migrations.AddField(
            model_name='iteninary',
            name='paths',
            field=models.ManyToManyField(to='iteninary.Path'),
        ),
        migrations.AddField(
            model_name='path',
            name='activities',
            field=models.ManyToManyField(to='iteninary.Activity'),
        ),
        migrations.AddField(
            model_name='path',
            name='housing',
            field=models.ManyToManyField(to='iteninary.Housing'),
        ),
        migrations.AddField(
            model_name='path',
            name='restaurants',
            field=models.ManyToManyField(to='iteninary.Restaurant'),
        ),
        migrations.AddField(
            model_name='path',
            name='transportation',
            field=models.ManyToManyField(to='iteninary.Transport'),
        ),
    ]
