# Generated by Django 2.2.3 on 2019-07-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteninary', '0002_auto_20190713_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='path',
            name='open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
